# Generated by Django 3.0.5 on 2020-05-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_acc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hashed_password',
        ),
    ]
