# Generated by Django 3.0.5 on 2020-05-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200506_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purchase_h_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='search_h_id',
        ),
    ]
