# Generated by Django 3.0.5 on 2020-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200508_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='def_prof.jpg', upload_to='profile_image'),
        ),
    ]
