# Generated by Django 3.0.5 on 2020-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200508_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
