# Generated by Django 3.0.5 on 2020-05-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200513_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='John', max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Doe', max_length=150),
        ),
    ]
