# Generated by Django 3.0.5 on 2020-05-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200506_1238'),
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_history',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_history',
            name='profile_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
    ]
