# Generated by Django 3.0.5 on 2020-05-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('histories', '0003_auto_20200507_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_history',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='search_history',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='acc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search_history',
            name='acc_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
