# Generated by Django 3.0.5 on 2020-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
